### ISSUE TITLE
src/kahootServer.py: Unfixed #signal

### ISSUE THREAD

**Issue by Toblobs** [Toblobs/kahootOnline#1]
- As of v1.0.7, some errors with signal (socket wrapper) have been bugging me:

> Upon running the code:

```
from netlib import Server, Signal
from netlib.net.server.connection import Connection
from uuid import uuid4
```

> A TypeError occurs:

```
def __init__(self, payload: dict | idict, route="/"):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

@suchasaltylemon and me are trying to fix the problem on his signal repo. Until then, production on kahootOnline will mainly be non-signal tests in src/tests.

**Comment by suchasaltylemon** [comment]
Fixed on latest version. Go to Signal github repo and download latest to fix. https://github.com/suchasaltylemon/Signal

**Comment by Toblobs** [comment]
Thanks @suchasaltylemon

**Comment by Toblobs** [comment]
Sam fixed bug, updated #signal
